export const GET_COMMUNITIES = 'GET_COMMUNITIES'
export const ADD_COMMUNITY = 'ADD_COMMUNITY'
export const UPDATE_COMMUNITY = 'UPDATE_COMMUNITY'
export const DELETE_COMMUNITY = 'DELETE_COMMUNITY'
export const SET_CURRENT_COMMUNITY = 'SET_CURRENT_COMMUNITY'

export const SET_CURRENT_DISCUSSION = 'SET_CURRENT_DISCUSSION'
export const TOGGLE_SIDE_NAV = 'TOGGLE_SIDE_NAV'
